<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config['per_page'] = 10;
$config['num_links'] = 2;
$config['full_tag_open'] = '<div class="pagination f-right"><ul>';
$config['full_tag_close'] = '</ul></div>';
$config['first_link'] = FALSE;
$config['last_link'] = FALSE;
$config['next_link'] = FALSE;
$config['prev_link'] = FALSE;
$config['cur_tag_open'] = '<li class="active">';
$config['cur_tag_close'] = '</li>';
$config['num_tag_open'] = '<li>';
$config['num_tag_close'] = '</li>';
$config['uri_segment'] = 3;